---
- name: Setup DBServer
  hosts: dbsrvgrp
  become: yes
  tasks:
  - name: Install Python MySQL dependency
    yum:
      name: MySQL-python
      state: present
  - name: Install MySQL server
    yum:
      name: mariadb-server
      state: present
  - name: Start & Enable mariadb service
    service:
      name: mariadb
      state: started
      enabled: yes
  - name: Create a new database with name 'acc19'
    mysql_db:
      name: 'acc19'
      state: present
  - name: Create database user with name 'admin'
    mysql_user:
      name: 'admin'
      password: '12345'
      priv: '*.*:ALL'
      state: present
