---
- name: Setup DBserver
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: Create a directory for downloading get-pip.py
      file:
        path: /opt/pyscripts
        state: directory
    - name: Download Python script for installing pip
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /opt/pyscripts/get-pip.py
    - name: Change access mode for get-pip.py
      file:
        path: /opt/pyscripts/get-pip.py
    - name: Run script get-pip.py to install pip
      shell:
        cmd: python /opt/pyscripts/get-pip.py
    - name: Install Python PyMySQL
      shell:
        cmd: pip install PyMySQL

    - name: Install MySQL server
      yum:
        name: mariadb-server
        state: present
    - name: Start & Enable maridb service
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Create a new database with name 'accounts'
      mysql_db:
        name: accounts
        state: present
    - name: Create database user with name 'admin'
      mysql_user:
        name: admin
        password: '12345'
        priv: '*.*:ALL'
        state: present
