---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USENAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
            optional: false # the secret MUST exist
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
            optional: false # the secret MUST exist
  restartPolicy: Never
