Vagrant.configure("2") do |config|
  # config.hostmanager.enabled = true 
  # config.hostmanager.manage_host = true
  
### Scriptbox VM  ####
  config.vm.define "scriptbox" do |scriptbox|
    scriptbox.vm.box = "bento/ubuntu-20.04"        #Ubuntu 20.04 LTS focal
    scriptbox.vm.box_version = "202309.09.0"
    scriptbox.vm.hostname = "scriptbox"
    scriptbox.vm.network "private_network", ip: "192.168.56.2"
    scriptbox.vm.synced_folder ".", "/vagrant"    #, disabled: true
    scriptbox.vm.provider "virtualbox" do |vb|
      vb.memory = "2000"
      vb.cpus = 1
    end
    scriptbox.vm.provision "shell", path: "./userdata/scriptbox-setup"  
  end
  
### Web01 VM  #### 
  config.vm.define "web01" do |web01|
    web01.vm.box = "centos/7"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.3"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1000"
      vb.cpus = 2
    end
    # web01.vm.provision "shell", path: "./userdata/web01-setup"  
  end

### Web02 VM ###
  config.vm.define "web02" do |web02|
    web02.vm.box = "centos/7"
    web02.vm.hostname = "web02"
    web02.vm.network "private_network", ip: "192.168.56.4"
    web02.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
      vb.cpus = 1
    end
    # web02.vm.provision "shell", path: "./userdata/web02-setup"  
  end

end
