#!/bin/bash
# A basic script for collecting information about the system
line="---------------------------------------------"
cat /etc/os-release; echo $line
echo "Current time: $(date)"; echo $line
echo "UPTIME time"; uptime -p; echo $line
echo "FREE memory"; free -h; echo $line
echo "WHO in logged"; who; echo $line
echo "Filesystem current state:"
df -h; echo $line
echo "List of home directories with size more of 100M:"
du -ht 100M -d2
