---
# handlers file for post-install
- name: Restart & enable NTP on Redhat
  service:
    name: ntpd
    state: restarted
    enabled: yes
  when: ansible_os_family == "RedHat"
- name: Restart & enable NTP on Debian
  service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_os_family == "Debian"

