---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  ports:
  - targetPort: vproapp-port      # it means "8080"
    port: 80
    protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer
