#!/bin/bash

# Variable Declaration
URL='https://www.tooplate.com/zip-templates/2098_health.zip'
ART_NAME='2098_health'
TEMPDIR="/tmp/webfiles"
SVC="httpd"

yum --help $> /dev/null

if [ $? -eq 0 ]; then
  # Set variables for CentOS
  echo "Running Setup on CentOS"
  PACKAGE="httpd wget unzip"
  # Installing Dependencies
  echo "########################################"
  echo "Installing packages."
  echo "########################################"
  sudo yum install $PACKAGE -y > /dev/null
  echo
else
  # Set variables for Ubuntu
  echo "Running Setup on Ubuntu"
  PACKAGE="apache2 wget unzip"
  SVC="apache2"
  # Installing Dependencies
  echo "########################################"
  echo "Installing packages."
  echo "########################################"
  sudo apt-get update -y
  sudo apt-get install $PACKAGE -y > /dev/null
  echo
fi

# Start & Enable Service
echo "########################################"
echo "Start & Enable Service"
echo "########################################"
sudo systemctl start $SVC
sudo systemctl enable $SVC
echo

# Creating Temp Directory
echo "########################################"
echo "Starting Artifact Deployment"
echo "########################################"
mkdir -p $TEMPDIR
cd $TEMPDIR
echo

wget $URL > /dev/null
unzip $ART_NAME.zip > /dev/null
sudo cp -r $ART_NAME/* /var/www/html/
echo

# Bounce Service
echo "########################################"
echo "Restarting service"
echo "########################################"
systemctl restart $SVC
echo

# Clean Up
echo "########################################"
echo "Removing Temporary Files"
echo "########################################"
rm -rf $TEMPDIR
echo

sudo systemctl status $SVC
ls /var/www/html/
