#!/bin/bash

# Variable Declaration
URL='https://www.tooplate.com/zip-templates/2098_health.zip'
ART_NAME='2098_health'
TEMPDIR="/tmp/webfiles"
SVC="httpd"

yum --help $> /dev/null

if [ $? -eq 0 ]
then
  # Set variables for CentOS
  echo "Running Setup on CentOS"
  PACKAGE="httpd wget unzip"
  sudo yum install $PACKAGE -y > /dev/null
  echo
else
  # Set variables for Ubuntu
  echo "Running Setup on Ubuntu"
  PACKAGE="apache2 wget unzip"
  SVC="apache2"
  sudo apt-get update -y
  sudo apt-get install $PACKAGE -y > /dev/null
  echo
fi

# Start & Enable Service
sudo systemctl start $SVC
sudo systemctl enable $SVC
echo

# Creating Temp Directory
mkdir -p $TEMPDIR
cd $TEMPDIR
echo

# Starting Artifact Deployment
wget $URL > /dev/null
unzip $ART_NAME.zip > /dev/null
sudo cp -r $ART_NAME/* /var/www/html/

# Bounce Service
systemctl restart $SVC

# Clean Up
rm -rf $TEMPDIR

