---
- name: Provisionng Server
  hosts: all
  become: true
  tasks:
    - name: Check distro
      debug:
        var: ansible_distribution

    - name: Add group
      group:
        name: devops
        state: present
        
    - name: Add users
      user:
        name: "{{item}}"
        state: present   # not obligatory if "present"
        groups: devops
      loop: "{{usernames}}"

    - name: Banner file /ets/motd
      copy:
        content: "This {{ansible_distribution}} is managed by Ansible.\n"
        dest: /etc/motd

    - name: Deploy NTP configuration file for RedHat
      template:
        src: templates/ntp_redhat.conf.j2
        dest: /etc/ntp.conf
      when: ansible_os_family == "RedHat"

    - name: Deploy NTP configuration file for Debian
      template:
        src: templates/ntp_debian.conf.j2
        dest: /etc/ntp.conf
      when: ansible_os_family == "Debian"

    - name: Restart & enable NTP on Redhat
      service:
        name: ntpd
        state: restarted
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Restart & enable NTP on Debian
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_os_family == "Debian"

