---
- name: Provisionng Server
  hosts: all
  become: true
  tasks:
    - name: Check distro
      debug:
        var: ansible_distribution

    - name: Install NTP on CentOS
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Install NTP on Ubuntu
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      when: ansible_distribution != "CentOS"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Start & enable NTP on Redhat
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start & enable NTP on Debian
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Add group
      group:
        name: devops
        state: present
        
    - name: Add users
      user:
        name: "{{item}}"
        state: present   # not obligatory if "present"
        groups: devops
      loop:
        - "chico"
        - "chicito"
        - "chiccitita"
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
