#!/bin/bash

# Развертывание простого веб-сервера с заготовкой сайта на Debian/RHEL

# Variable Declaration
URL='https://www.tooplate.com/zip-templates/2121_wave_cafe.zip'
ART_NAME='2121_wave_cafe'
TEMPDIR="/tmp/webfiles"
SVC="httpd"


# Installing Dependencies
echo "########################################"
echo "Installing packages."
echo "########################################"
echo

yum --help $> /dev/null
if [ $? -eq 0 ]; then
  # Set variables for CentOS
  echo "Running Setup on CentOS"
  PACKAGE="httpd wget unzip mc"
  sudo yum update -y
  sudo yum install $PACKAGE -y > /dev/null
else
  # Set variables for Ubuntu
  echo "Running Setup on Ubuntu"
  PACKAGE="apache2 wget unzip mc"
  SVC="apache2"
  sudo apt-get update -y
  sudo apt-get install $PACKAGE -y > /dev/null
fi

# Start & Enable Service
echo "########################################"
echo "Start & Enable Service"
echo "########################################"
sudo systemctl start $SVC
sudo systemctl enable $SVC
echo

# Creating Temp Directory
echo "########################################"
echo "Starting Artifact Deployment"
echo "########################################"
mkdir -p $TEMPDIR
cd $TEMPDIR
echo

wget $URL > /dev/null
unzip $ART_NAME.zip > /dev/null
sudo cp -r $ART_NAME/* /var/www/html/
echo

# Bounce Service
echo "########################################"
echo "Restarting service"
echo "########################################"
systemctl restart $SVC
echo

# Clean Up
echo "########################################"
echo "Removing Temporary Files"
echo "########################################"
rm -rf $TEMPDIR
echo

sudo systemctl status $SVC
ls /var/www/html/
