#!/bin/bash

# Развертывание простого веб-сервера с заготовкой сайта на Ubuntu v18

# Варианты заготовок сайтов
URL='https://www.tooplate.com/zip-templates/2098_health.zip'
ART_NAME='2098_health'
URL1='https://www.tooplate.com/zip-templates/2121_wave_cafe.zip'
ART_NAME1='2121_wave_cafe'
URL2=https:'//www.tooplate.com/zip-templates/2119_gymso_fitness.zip'
ART_NAME2='2119_gymso_fitness'
URL3='https://www.tooplate.com/zip-templates/2128_tween_agency.zip'
ART_NAME3='2128_tween_agency'

sudo apt update -y
sudo apt install apache2 wget unzip mc -y
wget $URL3
unzip $ART_NAME3.zip
sudo cp -r $ART_NAME3/* /var/www/html/
sudo systemctl restart apache2
export EDITOR=vim