AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CloudFormation template to create EC2 instance with security group

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId:  ami-010b814555e3268fa  # Ubuntu18.04  us-east-1
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref VprofileSG
      KeyName: 230724-ec2-t2micro
      # UserData:
      #   Fn::Base64: !Sub |
      #    #!/bin/bash
      #    sudo yum install java-17-amazon-corretto -y
      Tags:
        - Key: "Name"
          Value: !Join [ "-", [my,inst,from,AWS,CloudFormation] ]


  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh from MyIP & http to all IPv4
      GroupName: Vprofile-SG
      # VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80 
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

      # SecurityGroupEgress:
      #   - IpProtocol: tcp
      #     FromPort: 80
      #     ToPort: 80
      #     CidrIp: 0.0.0.0/0
      
