---
# Correct, Option A
SecurityGroupA:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: "Open HTTP (port 80) and SSH (port 22)"
    VpcId: !Ref VPC          
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Sub "${MyIp}"
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0   
    SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0  

---
# Correct, Option B
SecurityGroupB:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: "Open HTTP (port 80) and SSH (port 22)"
    VpcId: !Ref VPC  
       
SecurityGroupIngressMySSH:
  Type: AWS::EC2::SecurityGroupIngress
  Properties:
    Description: "Allow SSH connections from MyIp"
    GroupId: !Ref SecurityGroupB
    CidrIp: !Sub "${MyIp}"
    IpProtocol: tcp
    FromPort: 22
    ToPort: 22

SecurityGroupIngressHTTP:
  Type: AWS::EC2::SecurityGroupIngress
  Properties:
    Description: "Allow HTTP inbound traffic"
    GroupId: !Ref SecurityGroupB
    CidrIp: 0.0.0.0/0
    IpProtocol: tcp
    FromPort: 80
    ToPort: 80

SecurityGroupEgress:
  Type: AWS::EC2::SecurityGroupEgress
  Properties:
    Description: "Allow all outbound traffic"
    GroupId: !Ref SecurityGroupB
    CidrIp: 0.0.0.0/0  
    IpProtocol: tcp
    FromPort: 80
    ToPort: 80