---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - targetPort: vproapp-port      # it means "8080"
    port: 8090
    nodePort: 30001
    protocol: TCP
  selector:
    app: vproapp
  type: NodePort

