# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "geerlingguy/ubuntu2004"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
   config.vm.network "private_network", ip: "192.168.56.19"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # If you use this you may want to enable additional shared subfolders as
  # shown above.
   config.vm.synced_folder ".", "/vagrant" # , disabled: true

   config.vm.provider "virtualbox" do |vb|
     # vb.gui = true
     # Customize the amount of memory on the VM:
     vb.memory = "768"
     vb.cpus = 1
   end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL

    sudo apt-get update
    sudo apt-get install apache2 \
                 ghostscript \
                 libapache2-mod-php \
                 mysql-server \
                 php \
                 php-bcmath \
                 php-curl \
                 php-imagick \
                 php-intl \
                 php-json \
                 php-mbstring \
                 php-mysql \
                 php-xml \
                 php-zip -y
    
    sudo mkdir -p /srv/www
    sudo chown www-data: /srv/www
    curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www
    cp /vagrant/wordpress.conf /etc/apache2/sites-available/wordpress.conf
    
    sudo a2ensite wordpress
    sudo a2enmod rewrite
    sudo a2dissite 000-default
    sudo service apache2 reload
    
    mysql -u root -e 'CREATE DATABASE wordpress;'
    mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "asc4op";'
    mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'
    mysql -u root -e 'FLUSH PRIVILEGES;'

    sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
    sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
    sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
    sudo -u www-data sed -i 's/password_here/asc4op/' /srv/www/wordpress/wp-config.php

    # sudo -u www-data sed -i "s/'put your unique phrase here'/'h-y+(H<d.`IHP|(*o2=1aM~}X5nW<Dkvdk-+m7s>P/^!kqLZB_>i3e>_,Z|@;U}*'/1" /srv/www/wordpress/wp-config.php
    # sudo -u www-data sed -i "s/'put your unique phrase here'/'`cN|9j5#.mC}S1g7u8hUT:?FmgGHl-aBS;{6^Oq20Pj(+BF7Lhc%@_ORMn7]u9AT'/2" /srv/www/wordpress/wp-config.php
    # sudo -u www-data sed -i "s/'put your unique phrase here'/'wz#GiA~w<5S|74:,>S*Ka-.=gC-JR:*[A/am&~K:pUb#3K#O-T v~tOl9~^hf6%:'/3" /srv/www/wordpress/wp-config.php
    # sudo -u www-data sed -i "s/'put your unique phrase here'/'*7S$8w<xFH)U+$veoj>J5T5Y+Hu+yRrwo$V-pgMWts|>j| v@QZ2s?+p]U2+`ME;'/4" /srv/www/wordpress/wp-config.php
    # sudo -u www-data sed -i "s/'put your unique phrase here'/'HJlu){D$bLk0r -9Q7WL4Z|NyW-a{p80C, r|LAoD8|AsD=2--=Ob}[gP7zencnI'/5" /srv/www/wordpress/wp-config.php
    # sudo -u www-data sed -i "s/'put your unique phrase here'/'sv|,:ya2<3+OO.qi|:mh`Ie.v$R}+-v,YjUMde1> /AO+h[1IcVW}i/n}ZM9q`Ym'/6" /srv/www/wordpress/wp-config.php
    # sudo -u www-data sed -i "s/'put your unique phrase here'/'5;&gu^Gi`Mzjw6Bs<!~A{/+.Ua~c&nJ+~hl;u$u3,(LY2{v>/K>e%HAE@ZLB~S6T'/7" /srv/www/wordpress/wp-config.php
    # sudo -u www-data sed -i "s/'put your unique phrase here'/')eL06%Q,;,k=e9#H*+;3u^Y49G|j*N`?:?^iu5i|2.blqW0FOPWgp$`%x{Vm|&aU'/8" /srv/www/wordpress/wp-config.php
    
   SHELL
end
