---
- name: Understanding precedence of variables
  hosts: all
  become: yes
  #vars:                            # <--- The HIGHEST priority variables
  #  USRNM: 'playuser'
  #  COMM: 'A variable from the playbook'
  tasks:
  - name: Create a user
    user:
      name: "{{USRNM}}"
      comment: "{{COMM}}"
    register: USROUT
  - debug:
      var: USROUT.name
  - debug:
      var: USROUT.comment

