---
- name: Understanding precedence of variables
  hosts: all
  become: yes
  gather_facts: False   # w/o gathering facts
  vars:
    USRNM: 'playuser'
    COMM: 'A variable from the playbook'
  tasks:
  - name: Create a user
    user:
      name: "{{USRNM}}"
      comment: "{{COMM}}"
    register: USROUT
  - debug:
      var: USROUT
