Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### Jenkins VM  ####
  config.vm.define "jvm" do |jvm|
    jvm.vm.box = "ubuntu/jammy64"           #Ubuntu 22.04
    jvm.vm.hostname = "jvm01"
    jvm.vm.network "private_network", ip: "192.168.56.11"
    jvm.vm.synced_folder ".", "/vagrant"    #, disabled: true
    jvm.vm.provider "virtualbox" do |vb|
      vb.memory = "3200"
      vb.cpus = 1
    end
    jvm.vm.provision "shell", path: "./userdata/jenkins-setup"  
  end
  
### Nexus VM  #### 
  config.vm.define "nvm" do |nvm|
    nvm.vm.box = "centos/7"
    nvm.vm.hostname = "nvm01"
    nvm.vm.network "private_network", ip: "192.168.56.12"
    nvm.vm.synced_folder ".", "/vagrant"    #, disabled: true
    nvm.vm.provider "virtualbox" do |vb|
      vb.memory = "2400"
      vb.cpus = 1
    end
    nvm.vm.provision "shell", path: "./userdata/nexus-setup"  
  end

### SonarQube VM ###
  config.vm.define "svm" do |svm|
    svm.vm.box = "ubuntu/jammy64"           #Ubuntu 22.04
    svm.vm.hostname = "svm01"
    svm.vm.network "private_network", ip: "192.168.56.19"
    # svm.vm.synced_folder ".", "/vagrant"    #, disabled: true
    svm.vm.provision "shell", path: "./userdata/sonar-setup"  
    svm.vm.provider "virtualbox" do |vb|
      vb.memory = "3000"
      vb.cpus = 1
    end
  end

end
