Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
    web01.vm.hostname = "web01"
	  web01.vm.network "private_network", ip: "192.168.56.11"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "768"
      vb.cpus = 1
	  end
    web01.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo echo "## vagrant-hostmanager-start\n192.168.56.11 web01\n192.168.56.12 app01\n192.168.56.14 mc01\n192.168.56.15 db01\n192.168.56.16 rmq01\n## vagrant-hostmanager-end" >> /etc/hosts
    SHELL
  end
  
### tomcat vm ###
  config.vm.define "app01" do |app01|
    app01.vm.box = "geerlingguy/centos7"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
	  app01.vm.provider "virtualbox" do |vb|
      vb.memory = "768"
      vb.cpus = 1
	  end
    app01.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      yum install epel-release -y
      yum install java-11-openjdk java-11-openjdk-devel -y
      yum install wget maven git -y
      sudo echo "## vagrant-hostmanager-start\n192.168.56.11	web01\n192.168.56.12	app01\n192.168.56.14	mc01\n192.168.56.15	db01\n192.168.56.16	rmq01\n## vagrant-hostmanager-end" >> /etc/hosts
      cd /tmp/
      wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.75/bin/apache-tomcat-9.0.75.tar.gz
      tar xzvf apache-tomcat-9.0.75.tar.gz
      useradd --home-dir /usr/local/tomcat --shell /sbin/nologin tomcat
      cp -r /tmp/apache-tomcat-9.0.75/* /usr/local/tomcat/
      chown -R tomcat.tomcat /usr/local/tomcat
    SHELL
  end
   
### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "geerlingguy/centos7"
	  rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.16"
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
	  end
    rmq01.vm.provision "shell", inline: <<-SHELL
      yum update -y
      yum install epel-release -y
      yum install wget -y
      sudo echo "## vagrant-hostmanager-start\n192.168.56.11	web01\n192.168.56.12	app01\n192.168.56.14	mc01\n192.168.56.15	db01\n192.168.56.16	rmq01\n## vagrant-hostmanager-end" >> /etc/hosts
      cd /tmp/
      wget http://packages.erlang-solutions.com/erlang-solutions-2.0-1.noarch.rpm
      rpm -Uvh erlang-solutions-2.0-1.noarch.rpm
      yum install erlang socat -y
      curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash
      yum install rabbitmq-server -y
      systemctl start rabbitmq-server
      systemctl enable rabbitmq-server
      sh -c 'echo "[{rabbit, [{loopback_users, []}]}]." > /etc/rabbitmq/rabbitmq.config'
      rabbitmqctl add_user test test
      rabbitmqctl set_user_tags test administrator
      systemctl restart rabbitmq-server
    SHELL
  end
  
### Memcache vm  #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "geerlingguy/centos7"
	  mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
	  end
    mc01.vm.provision "shell", inline: <<-SHELL
      yum update -y
      sudo echo "## vagrant-hostmanager-start\n192.168.56.11	web01\n192.168.56.12	app01\n192.168.56.14	mc01\n192.168.56.15	db01\n192.168.56.16	rmq01\n## vagrant-hostmanager-end" >> /etc/hosts
      yum install epel-release -y
      yum install memcached -y
      systemctl start memcached
      systemctl enable memcached
      memcached -p 11211 -U 11111 -u memcached -d
      # для проверки
      # ss -tunlp | grep 11211
    SHELL
  end
  
### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "geerlingguy/centos7"
	  db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
	  end
    db01.vm.provision "shell", inline: <<-SHELL
      yum update -y
      yum install epel-release -y
      yum install git mariadb-server -y
      systemctl start mariadb
      systemctl enable mariadb
      sudo echo "## vagrant-hostmanager-start\n192.168.56.11	web01\n192.168.56.12	app01\n192.168.56.14	mc01\n192.168.56.15	db01\n192.168.56.16	rmq01\n## vagrant-hostmanager-end" >> /etc/hosts
    SHELL
  end
end
