---
- name: Learning fact variables
  hosts: all
  tasks: 
  - name: Print OS name
    debug: 
      var: ansible_distribution
  - name: Print Real Memory details
    debug: 
      var: ansible_memory_mb.real.free
  - name: Print CPU details
    debug:
      var: ansible_processor[2]
